const scenes=[...document.querySelectorAll('.scene')], counter=document.querySelector('#counter'), dots=document.querySelector('#navdots'), progress=document.querySelector('#progress');
scenes.forEach((s,i)=>{const b=document.createElement('button');b.setAttribute('aria-label','Ir para '+s.dataset.label||('seção '+(i+1)));b.onclick=()=>s.scrollIntoView();dots.appendChild(b)});
const dotButtons=[...dots.children];
let current=0;
const setCurrent=i=>{current=i;counter.textContent=String(i+1).padStart(2,'0')+' / '+String(scenes.length).padStart(2,'0');dotButtons.forEach((d,j)=>d.classList.toggle('active',j===i));progress.style.width=((i+1)/scenes.length*100)+'%'};
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)setCurrent(scenes.indexOf(e.target))}),{threshold:.62});scenes.forEach(s=>io.observe(s));
const go=d=>scenes[Math.max(0,Math.min(scenes.length-1,current+d))].scrollIntoView({behavior:'smooth'});
document.querySelector('#next').onclick=()=>go(1);document.querySelector('#prev').onclick=()=>go(-1);
document.addEventListener('keydown',e=>{if(['ArrowDown','ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();go(1)}if(['ArrowUp','ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();go(-1)}if(e.key==='Home')scenes[0].scrollIntoView();if(e.key==='End')scenes.at(-1).scrollIntoView()});
const dlg=document.querySelector('#speakerDialog');document.querySelector('#speakerBtn').onclick=()=>dlg.showModal();document.querySelector('#closeSpeaker').onclick=()=>dlg.close();dlg.onclick=e=>{if(e.target===dlg)dlg.close()};
document.querySelector('#presentBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();
const areas={tech:['Tecnologia','Código, incidentes e documentação','IA organiza contexto → sugere caminhos → profissional valida e implementa'],adm:['Administração','Relatórios, processos e cenários','IA consolida dados → identifica padrões → profissional interpreta e decide'],cont:['Ciências Contábeis','Documentos, conciliações e análises','IA extrai e classifica → sinaliza diferenças → profissional valida e responde'],rh:['Recursos Humanos','Currículos, competências e rotinas','IA organiza informações → apoia triagem → profissional contextualiza e decide'],log:['Logística','Estoque, demanda e rotas','IA cruza sinais → apoia cenários → profissional define restrições e decisão'],edu:['Educação','Aprendizagem, feedback e acompanhamento','IA organiza evidências → apoia personalização → educador interpreta e intervém']};
const card=document.querySelector('#areaCard');function render(k){const a=areas[k];card.innerHTML='<h3>'+a[0]+'</h3><p class="lead">'+a[1]+'</p><p class="mini-flow">'+a[2]+'</p>'}render('tech');
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');render(t.dataset.area)});
document.querySelectorAll('.levels button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.levels button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});
setCurrent(0);
document.querySelector('#toTop').onclick=()=>scenes[0].scrollIntoView({behavior:'smooth'});document.querySelector('#toBottom').onclick=()=>scenes.at(-1).scrollIntoView({behavior:'smooth'});

const cases={
tech:{title:'Tecnologia',tag:'Caso · Operações assistidas por IA',steps:['Logs e contexto','IA organiza sinais','Profissional investiga','Ação validada'],example:'Exemplo: reunir logs de uma aplicação, resumir padrões de erro e sugerir hipóteses. A IA reduz o trabalho de organização; diagnóstico, impacto e mudança permanecem sob validação profissional.'},
adm:{title:'Administração',tag:'Caso · Automação inteligente',steps:['Documentos e indicadores','IA extrai e consolida','Gestor compara cenários','Decisão e acompanhamento'],example:'Exemplo: consolidar relatórios recorrentes de áreas diferentes, identificar variações e produzir uma síntese inicial para uma reunião de gestão.'},
cont:{title:'Ciências Contábeis',tag:'Caso · Conciliação assistida',steps:['Documentos e transações','IA classifica','Profissional verifica divergências','Registro e decisão'],example:'Exemplo: apoiar a organização documental e sinalizar diferenças para revisão. Critérios contábeis, conformidade e responsabilidade continuam com o profissional.'},
rh:{title:'Recursos Humanos',tag:'Caso · Organização de competências',steps:['Perfis e requisitos','IA estrutura informações','RH contextualiza','Decisão humana'],example:'Exemplo: estruturar competências presentes em currículos e comparar com requisitos previamente definidos, mantendo avaliação, contexto e decisão com a equipe de RH.'},
log:{title:'Logística',tag:'Caso · Cenários operacionais',steps:['Estoque, demanda e rotas','IA cruza sinais','Profissional define restrições','Plano operacional'],example:'Exemplo: combinar histórico de demanda e estoque para apoiar cenários de reposição, que depois são avaliados à luz de prazo, custo e restrições reais.'},
edu:{title:'Educação',tag:'Caso real · Paraná + Google',steps:['Redação digital','Gemini aplica rubrica','Professor revisa','Feedback ao estudante'],example:'No Paraná, o Google documenta um fluxo em que a redação passa pelo Gemini, recebe comentários baseados em rubricas e chega ao professor com observações para revisão e acompanhamento. A rede atende mais de 1,2 milhão de estudantes.',link:'https://edu.google.com/intl/ALL_br/resources/customer-stories/brazil-parana/'}
};
const caseDlg=document.querySelector('#caseDialog'),caseContent=document.querySelector('#caseContent');
function openCase(){const active=document.querySelector('.tab.active');const x=cases[active.dataset.area];caseContent.innerHTML='<div class="case-head"><div><p class="case-badge">'+x.tag+'</p><h2>'+x.title+'</h2></div></div><div class="case-flow">'+x.steps.map((s,i)=>'<article><small>0'+(i+1)+'</small><strong>'+s+'</strong></article>').join('')+'</div><p class="case-example">'+x.example+'</p>';caseContent.innerHTML+=(x.link?'<div class="evidence-links"><a href="'+x.link+'" target="_blank" rel="noopener">Ver evidência na fonte oficial ↗</a></div>':'');caseDlg.showModal()}
document.querySelector('#caseBtn').onclick=openCase;document.querySelector('#closeCase').onclick=()=>caseDlg.close();caseDlg.onclick=e=>{if(e.target===caseDlg)caseDlg.close()};

const mediaDlg=document.querySelector('#mediaDialog'),mediaContent=document.querySelector('#mediaContent');
const media={
timeline:{kind:'visual',title:'Foxconn: a fábrica existe primeiro no digital',text:'A Foxconn usa gêmeos digitais com NVIDIA Omniverse para projetar e operar fábricas. Linhas, robôs e logística podem ser simulados antes da implantação física; a NVIDIA relata simulações térmicas até 150× mais rápidas. A provocação deixa de ser “o que a IA responde?” e passa a ser “o que podemos testar antes de executar no mundo real?”.',visual:'<div class="demo-network"><span>FÁBRICA REAL<br>dados</span><span>GÊMEO DIGITAL<br>Omniverse</span><span>SIMULAÇÃO<br>cenários</span><span>ROBÔS<br>Isaac Sim</span><span>DECISÃO<br>engenharia</span><span>FÁBRICA<br>implantação</span></div><p class="case-source">Caso real · Foxconn + NVIDIA</p>',link:'https://www.nvidia.com/pt-br/case-studies/foxconn-develops-physical-ai-enabled-smart-factories-with-digital-twins/'},
agents:{kind:'visual',title:'i-Tom: IA generativa entra na operação',text:'A i-Tom Solutions recebia cerca de 600 consultas por dia. Segundo a AWS, após uma prova de conceito de 4–5 semanas, um assistente com Amazon Bedrock chegou à produção em uma semana e passou a atender centenas de interações por dia. O caso ajuda a mostrar a passagem de “usar IA” para incorporar IA a um processo de negócio.',visual:'<div class="demo-network"><span>~600/DIA<br>consultas</span><span>BEDROCK<br>IA generativa</span><span>ASSISTENTE<br>contexto</span><span>RESPOSTA<br>automatizada</span><span>TIME HUMANO<br>exceções</span><span>ESCALA<br>operação</span></div><p class="case-source">Caso real · i-Tom Solutions + AWS</p>',link:'https://aws.amazon.com/solutions/case-studies/i-tom-solutions-case-study/'},
vision:{kind:'visual',title:'Foxconn: robôs de IA física apoiando hospitais',text:'Em um caso publicado pela NVIDIA, robôs autônomos foram usados em tarefas de transporte hospitalar. A empresa relata economia de 2–3 horas por dia de trabalho de enfermagem relacionado a transporte, validação por simulação e 98% de precisão em tarefas de navegação. É um exemplo para discutir IA saindo da tela e entrando no ambiente físico.',visual:'<div class="demo-network"><span>HOSPITAL<br>demanda</span><span>SENSORES<br>percepção</span><span>IA FÍSICA<br>decisão</span><span>ROBÔ<br>transporte</span><span>EQUIPE<br>supervisão</span><span>TEMPO<br>assistência</span></div><p class="case-source">Caso real · Foxconn + NVIDIA</p>',link:'https://www.nvidia.com/en-us/case-studies/foxconn/'}
};
function openMedia(k){const m=media[k];const visual=m.kind==='video'?'<iframe src="'+m.video+'" title="'+m.title+'" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>':'<div class="media-visual">'+m.visual+'</div>';mediaContent.innerHTML='<div class="media-stage">'+visual+'<div class="media-copy"><p class="kicker">Explorar</p><h2>'+m.title+'</h2><p>'+m.text+'</p>'+(m.link?'<a href="'+m.link+'" target="_blank" rel="noopener">Ver caso na fonte oficial ↗</a>':'')+'</div></div>';mediaDlg.showModal()}
document.querySelectorAll('.media-btn').forEach(b=>b.onclick=()=>openMedia(b.dataset.media));document.querySelector('#closeMedia').onclick=()=>{mediaDlg.close();mediaContent.innerHTML=''};mediaDlg.onclick=e=>{if(e.target===mediaDlg){mediaDlg.close();mediaContent.innerHTML=''}};

const evidenceDlg=document.querySelector('#evidenceDialog'),evidenceContent=document.querySelector('#evidenceContent');
const evidence={
nvidia:{brand:'NVIDIA + FOXCONN · MANUFATURA',q:'E se a fábrica pudesse errar no digital antes de errar no mundo físico?',number:'150×',label:'simulação CFD mais rápida',metric:'A Foxconn conecta fábricas virtuais a dados operacionais e simula células robóticas e logística antes da implantação física.',proof:'A NVIDIA documenta simulações térmicas em minutos em vez de horas e relata que a Foxconn estima reduzir em cerca de 50% o tempo de configuração e planejamento de fábricas.',take:'Transformação aqui não é trocar uma ferramenta: é mudar onde o risco, o teste e a decisão acontecem.',links:[['Caso oficial NVIDIA','https://www.nvidia.com/pt-br/case-studies/foxconn-develops-physical-ai-enabled-smart-factories-with-digital-twins/']]},
aws:{brand:'AWS + i-TOM · OPERAÇÕES',q:'Quando uma fila de atendimento deixa de crescer junto com a equipe?',number:'200–600',label:'consultas escritas por dia',metric:'A i-Tom construiu um assistente de IA generativa com Amazon Bedrock, RAG, Lambda e OpenSearch para responder perguntas usando sua base de conhecimento.',proof:'Após uma PoC de 4–5 semanas, a arquitetura validada foi implantada em produção em uma semana. A AWS relata centenas de consultas tratadas diariamente pelo assistente.',take:'O salto acontece quando IA deixa de ser uma conversa isolada e passa a integrar conhecimento, infraestrutura e rotina operacional.',links:[['Caso oficial AWS','https://aws.amazon.com/solutions/case-studies/i-tom-solutions-case-study/']]},
cisco:{brand:'CISCO · CIBERSEGURANÇA',q:'E se a rede pudesse participar da resposta antes do próximo handoff humano?',number:'50%',label:'melhora no tempo de resposta a incidentes',metric:'A Cisco descreve a transformação de sua rede global em uma arquitetura self-defending para responder a ameaças impulsionadas por IA.',proof:'O caso reporta redução de handoffs manuais, adoção segura de ferramentas de IA generativa e avanço na contenção de ameaças sem retirar a rede do ar.',take:'A provocação não é “IA na segurança”, mas infraestrutura passando a participar ativamente da proteção.',links:[['Caso + vídeo 2:37','https://www.cisco.com/site/us/en/solutions/cisco-on-cisco/self-defending-network.html']]},
google:{brand:'GOOGLE + PARANÁ · EDUCAÇÃO',q:'E se o professor recebesse a redação já com uma primeira camada de feedback?',number:'1,2M+',label:'estudantes na rede pública',metric:'No Paraná, redações digitais passam pelo Gemini, que adiciona comentários com base em rubricas predefinidas antes da revisão do professor.',proof:'O Google relata mais de 2 milhões de licenças do Workspace for Education e descreve o objetivo de ampliar a frequência da escrita sem retirar o olhar crítico docente.',take:'Automação e personalização podem coexistir quando a tecnologia reorganiza a tarefa e preserva a intervenção pedagógica.',links:[['Caso oficial Google','https://edu.google.com/intl/ALL_br/resources/customer-stories/brazil-parana/']]}
};
function openEvidence(k){const x=evidence[k];evidenceContent.innerHTML='<div class="evidence-layout"><div class="evidence-metric"><p class="kicker">'+x.brand+'</p><div class="evidence-number">'+x.number+'</div><div class="evidence-label">'+x.label+'</div><p>'+x.metric+'</p></div><div class="evidence-body"><p class="kicker">Evidência para provocar</p><h2 class="evidence-question">'+x.q+'</h2><p class="proof">'+x.proof+'</p><p class="evidence-takeaway">'+x.take+'</p><div class="evidence-links">'+x.links.map(a=>'<a href="'+a[1]+'" target="_blank" rel="noopener">'+a[0]+' ↗</a>').join('')+'</div></div></div>';evidenceDlg.showModal()}
document.querySelectorAll('.evidence-card,.story-card').forEach(b=>b.onclick=()=>openEvidence(b.dataset.evidence));document.querySelector('#closeEvidence').onclick=()=>evidenceDlg.close();evidenceDlg.onclick=e=>{if(e.target===evidenceDlg)evidenceDlg.close()};

const demoDlg=document.querySelector('#demoDialog'),demoSteps=[...document.querySelectorAll('#liveFlow>div')],demoStatus=document.querySelector('#demoStatus');let demoTimer=null,demoIndex=0;
function resetDemo(){clearInterval(demoTimer);demoTimer=null;demoIndex=0;demoSteps.forEach(x=>x.classList.remove('active'));demoStatus.textContent='Pronto para iniciar.'}
function runDemo(){resetDemo();demoSteps[0].classList.add('active');demoStatus.textContent='Solicitação recebida.';demoIndex=1;demoTimer=setInterval(()=>{if(demoIndex>=demoSteps.length){clearInterval(demoTimer);demoTimer=null;demoStatus.textContent='Fluxo concluído com validação humana.';return}demoSteps[demoIndex].classList.add('active');demoStatus.textContent=['','IA interpretando a intenção.','Consultando dados autorizados.','Preparando proposta.','Aguardando validação humana.','Resultado liberado.'][demoIndex];demoIndex++},850)}
document.querySelector('#demoBtn').onclick=()=>{resetDemo();demoDlg.showModal()};document.querySelector('#runDemo').onclick=runDemo;document.querySelector('#resetDemo').onclick=resetDemo;document.querySelector('#closeDemo').onclick=()=>{resetDemo();demoDlg.close()};demoDlg.onclick=e=>{if(e.target===demoDlg){resetDemo();demoDlg.close()}};
