const scenes=[...document.querySelectorAll('.scene')], counter=document.querySelector('#counter'), dots=document.querySelector('#navdots'), progress=document.querySelector('#progress');
scenes.forEach((s,i)=>{const b=document.createElement('button');b.setAttribute('aria-label','Ir para '+s.dataset.label||('seção '+(i+1)));b.onclick=()=>s.scrollIntoView();dots.appendChild(b)});
const dotButtons=[...dots.children];
let current=0;
const setCurrent=i=>{current=i;counter.textContent=String(i+1).padStart(2,'0')+' / '+String(scenes.length).padStart(2,'0');dotButtons.forEach((d,j)=>d.classList.toggle('active',j===i));progress.style.width=((i+1)/scenes.length*100)+'%'};
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)setCurrent(scenes.indexOf(e.target))}),{threshold:.62});scenes.forEach(s=>io.observe(s));
const go=d=>scenes[Math.max(0,Math.min(scenes.length-1,current+d))].scrollIntoView({behavior:'smooth'});
document.querySelector('#next').onclick=()=>go(1);document.querySelector('#prev').onclick=()=>go(-1);
document.addEventListener('keydown',e=>{if(['ArrowDown','ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();go(1)}if(['ArrowUp','ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();go(-1)}if(e.key==='Home')scenes[0].scrollIntoView();if(e.key==='End')scenes.at(-1).scrollIntoView()});
const dlg=document.querySelector('#speakerDialog');document.querySelector('#speakerBtn').onclick=()=>dlg.showModal();document.querySelector('#closeSpeaker').onclick=()=>dlg.close();dlg.onclick=e=>{if(e.target===dlg)dlg.close()};
document.querySelector('#presentBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();
const areas={tech:['Tecnologia','Código, incidentes e documentação','IA organiza contexto → sugere caminhos → profissional valida e implementa'],adm:['Administração','Relatórios, processos e cenários','IA consolida dados → identifica padrões → profissional interpreta e decide'],cont:['Ciências Contábeis','Documentos, conciliações e análises','IA extrai e classifica → sinaliza diferenças → profissional valida e responde'],rh:['Recursos Humanos','Currículos, competências e rotinas','IA organiza informações → apoia triagem → profissional contextualiza e decide'],log:['Logística','Estoque, demanda e rotas','IA cruza sinais → apoia cenários → profissional define restrições e decisão'],edu:['Educação','Aprendizagem, feedback e acompanhamento','IA organiza evidências → apoia personalização → educador interpreta e intervém']};
const card=document.querySelector('#areaCard');function render(k){const a=areas[k];card.innerHTML='<h3>'+a[0]+'</h3><p class="lead">'+a[1]+'</p><p class="mini-flow">'+a[2]+'</p>'}render('tech');
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');render(t.dataset.area)});
document.querySelectorAll('.levels button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.levels button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});
setCurrent(0);
document.querySelector('#toTop').onclick=()=>scenes[0].scrollIntoView({behavior:'smooth'});document.querySelector('#toBottom').onclick=()=>scenes.at(-1).scrollIntoView({behavior:'smooth'});

const cases={
tech:{title:'Tecnologia',tag:'Caso · Operações assistidas por IA',steps:['Logs e contexto','IA organiza sinais','Profissional investiga','Ação validada'],example:'Exemplo: reunir logs de uma aplicação, resumir padrões de erro e sugerir hipóteses. A IA reduz o trabalho de organização; diagnóstico, impacto e mudança permanecem sob validação profissional.'},
adm:{title:'Administração',tag:'Caso · Automação inteligente',steps:['Documentos e indicadores','IA extrai e consolida','Gestor compara cenários','Decisão e acompanhamento'],example:'Exemplo: consolidar relatórios recorrentes de áreas diferentes, identificar variações e produzir uma síntese inicial para uma reunião de gestão.'},
cont:{title:'Ciências Contábeis',tag:'Caso · Conciliação assistida',steps:['Documentos e transações','IA classifica','Profissional verifica divergências','Registro e decisão'],example:'Exemplo: apoiar a organização documental e sinalizar diferenças para revisão. Critérios contábeis, conformidade e responsabilidade continuam com o profissional.'},
rh:{title:'Recursos Humanos',tag:'Caso · Organização de competências',steps:['Perfis e requisitos','IA estrutura informações','RH contextualiza','Decisão humana'],example:'Exemplo: estruturar competências presentes em currículos e comparar com requisitos previamente definidos, mantendo avaliação, contexto e decisão com a equipe de RH.'},
log:{title:'Logística',tag:'Caso · Cenários operacionais',steps:['Estoque, demanda e rotas','IA cruza sinais','Profissional define restrições','Plano operacional'],example:'Exemplo: combinar histórico de demanda e estoque para apoiar cenários de reposição, que depois são avaliados à luz de prazo, custo e restrições reais.'},
edu:{title:'Educação',tag:'Caso · Personalização e feedback',steps:['Evidências de aprendizagem','IA organiza padrões','Educador interpreta','Intervenção pedagógica'],example:'Exemplo: sintetizar evidências de interação e desempenho para apoiar feedback e acompanhamento. A intervenção pedagógica é definida pelo educador.'}
};
const caseDlg=document.querySelector('#caseDialog'),caseContent=document.querySelector('#caseContent');
function openCase(){const active=document.querySelector('.tab.active');const x=cases[active.dataset.area];caseContent.innerHTML='<div class="case-head"><div><p class="case-badge">'+x.tag+'</p><h2>'+x.title+'</h2></div></div><div class="case-flow">'+x.steps.map((s,i)=>'<article><small>0'+(i+1)+'</small><strong>'+s+'</strong></article>').join('')+'</div><p class="case-example">'+x.example+'</p>';caseDlg.showModal()}
document.querySelector('#caseBtn').onclick=openCase;document.querySelector('#closeCase').onclick=()=>caseDlg.close();caseDlg.onclick=e=>{if(e.target===caseDlg)caseDlg.close()};

const mediaDlg=document.querySelector('#mediaDialog'),mediaContent=document.querySelector('#mediaContent');
const media={
timeline:{kind:'visual',title:'Foxconn: a fábrica existe primeiro no digital',text:'A Foxconn usa gêmeos digitais com NVIDIA Omniverse para projetar e operar fábricas. Linhas, robôs e logística podem ser simulados antes da implantação física; a NVIDIA relata simulações térmicas até 150× mais rápidas. A provocação deixa de ser “o que a IA responde?” e passa a ser “o que podemos testar antes de executar no mundo real?”.',visual:'<div class="demo-network"><span>FÁBRICA REAL<br>dados</span><span>GÊMEO DIGITAL<br>Omniverse</span><span>SIMULAÇÃO<br>cenários</span><span>ROBÔS<br>Isaac Sim</span><span>DECISÃO<br>engenharia</span><span>FÁBRICA<br>implantação</span></div><p class="case-source">Caso real · Foxconn + NVIDIA</p>',link:'https://www.nvidia.com/pt-br/case-studies/foxconn-develops-physical-ai-enabled-smart-factories-with-digital-twins/'},
agents:{kind:'visual',title:'i-Tom: IA generativa entra na operação',text:'A i-Tom Solutions recebia cerca de 600 consultas por dia. Segundo a AWS, após uma prova de conceito de 4–5 semanas, um assistente com Amazon Bedrock chegou à produção em uma semana e passou a atender centenas de interações por dia. O caso ajuda a mostrar a passagem de “usar IA” para incorporar IA a um processo de negócio.',visual:'<div class="demo-network"><span>~600/DIA<br>consultas</span><span>BEDROCK<br>IA generativa</span><span>ASSISTENTE<br>contexto</span><span>RESPOSTA<br>automatizada</span><span>TIME HUMANO<br>exceções</span><span>ESCALA<br>operação</span></div><p class="case-source">Caso real · i-Tom Solutions + AWS</p>',link:'https://aws.amazon.com/solutions/case-studies/i-tom-solutions-case-study/'},
vision:{kind:'visual',title:'Foxconn: robôs de IA física apoiando hospitais',text:'Em um caso publicado pela NVIDIA, robôs autônomos foram usados em tarefas de transporte hospitalar. A empresa relata economia de 2–3 horas por dia de trabalho de enfermagem relacionado a transporte, validação por simulação e 98% de precisão em tarefas de navegação. É um exemplo para discutir IA saindo da tela e entrando no ambiente físico.',visual:'<div class="demo-network"><span>HOSPITAL<br>demanda</span><span>SENSORES<br>percepção</span><span>IA FÍSICA<br>decisão</span><span>ROBÔ<br>transporte</span><span>EQUIPE<br>supervisão</span><span>TEMPO<br>assistência</span></div><p class="case-source">Caso real · Foxconn + NVIDIA</p>',link:'https://www.nvidia.com/en-us/case-studies/foxconn/'}
};
function openMedia(k){const m=media[k];const visual=m.kind==='video'?'<iframe src="'+m.video+'" title="'+m.title+'" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>':'<div class="media-visual">'+m.visual+'</div>';mediaContent.innerHTML='<div class="media-stage">'+visual+'<div class="media-copy"><p class="kicker">Explorar</p><h2>'+m.title+'</h2><p>'+m.text+'</p>'+(m.link?'<a href="'+m.link+'" target="_blank" rel="noopener">Ver caso na fonte oficial ↗</a>':'')+'</div></div>';mediaDlg.showModal()}
document.querySelectorAll('.media-btn').forEach(b=>b.onclick=()=>openMedia(b.dataset.media));document.querySelector('#closeMedia').onclick=()=>{mediaDlg.close();mediaContent.innerHTML=''};mediaDlg.onclick=e=>{if(e.target===mediaDlg){mediaDlg.close();mediaContent.innerHTML=''}};

const evidenceDlg=document.querySelector('#evidenceDialog'),evidenceContent=document.querySelector('#evidenceContent');
const evidence={
nvidia:{brand:'NVIDIA · Physical AI',q:'Uma fábrica pode ser testada antes de existir?',big:'REAL → SIM → REAL',metric:'A NVIDIA descreve fluxos em que digital twins simulam fábricas, robôs e interação com pessoas antes da implantação física.',proof:'Na GTC 2026, Foxconn e NVIDIA apresentaram uma AI factory no Texas usando Omniverse para simulação e monitoramento; sessões técnicas também mostram Isaac + Omniverse em fluxos de Physical AI.',links:[['Caso Foxconn · GTC 2026','https://www.nvidia.com/en-us/on-demand/session/gtc26-s81508/'],['Treinamentos NVIDIA DLI','https://www.nvidia.com/en-us/training/']]},
aws:{brand:'AWS · Automação inteligente',q:'E se um vídeo de treinamento virasse um processo executável?',big:'VÍDEO → SOP → AGENTE',metric:'Um caso técnico recente da AWS transforma vídeos de treinamento em SOPs, usa RAG para orientar resolução e agentes para automatizar etapas, mantendo human-in-the-loop.',proof:'O exemplo conecta exatamente a ideia da palestra: sair do prompt isolado e redesenhar o processo, com conhecimento, modelos, ferramentas, risco de SLA e validação humana.',links:[['Caso AWS · Support Operations','https://aws.amazon.com/blogs/machine-learning/modernizing-and-scaling-support-operations-with-generative-ai-on-aws/'],['AWS Artificial Intelligence','https://aws.amazon.com/blogs/machine-learning/']]},
cisco:{brand:'Cisco · Rede + IA',q:'Quando a rede deixa de ser apenas infraestrutura?',big:'REDE → SENSOR → DEFESA',metric:'A Cisco documenta sua arquitetura self-defending network para responder a ameaças aceleradas por IA e oferece um vídeo curto de 2:37 no próprio caso.',proof:'Outro caso de 2026 mostra infraestrutura de IA com compute, GPUs NVIDIA e networking Cisco, implantada em três meses e suportando mais de 25 casos de uso.',links:[['Self-Defending Network','https://www.cisco.com/site/us/en/solutions/cisco-on-cisco/self-defending-network.html'],['AI-Ready Infrastructure','https://www.cisco.com/site/us/en/solutions/cisco-on-cisco/ai-ready-infrastructure.html']]},
google:{brand:'Google · Educação',q:'IA pode ampliar feedback sem retirar o professor do processo?',big:'FEEDBACK + CONTEXTO HUMANO',metric:'No Paraná, um caso publicado pelo Google descreve redações que recebem comentários do Gemini com rubricas predefinidas antes da revisão e orientação do professor.',proof:'O caso conecta personalização, automação de tarefas e acompanhamento pedagógico. A página também relata uso em escala na rede pública e apresenta material visual do projeto.',links:[['Caso Paraná · Gemini for Education','https://edu.google.com/intl/ALL_br/resources/customer-stories/brazil-parana/'],['Casos de impacto Google','https://edu.google.com/intl/ALL_br/resources/customer-stories/']]}
};
function openEvidence(k){const x=evidence[k];evidenceContent.innerHTML='<div class="evidence-layout"><div class="evidence-metric"><p class="kicker">'+x.brand+'</p><div class="big">'+x.big+'</div><p>'+x.metric+'</p></div><div class="evidence-body"><p class="kicker">Evidência para provocar</p><h2>'+x.q+'</h2><p class="proof">'+x.proof+'</p><div class="evidence-links">'+x.links.map(a=>'<a href="'+a[1]+'" target="_blank" rel="noopener">'+a[0]+' ↗</a>').join('')+'</div></div></div>';evidenceDlg.showModal()}
document.querySelectorAll('.evidence-card').forEach(b=>b.onclick=()=>openEvidence(b.dataset.evidence));document.querySelector('#closeEvidence').onclick=()=>evidenceDlg.close();evidenceDlg.onclick=e=>{if(e.target===evidenceDlg)evidenceDlg.close()};
