const scenes=[...document.querySelectorAll('.scene')], counter=document.querySelector('#counter'), dots=document.querySelector('#navdots'), progress=document.querySelector('#progress');
scenes.forEach((s,i)=>{const b=document.createElement('button');b.setAttribute('aria-label','Ir para '+s.dataset.label||('seção '+(i+1)));b.onclick=()=>s.scrollIntoView();dots.appendChild(b)});
const dotButtons=[...dots.children];
let current=0;
const setCurrent=i=>{current=i;counter.textContent=String(i+1).padStart(2,'0')+' / '+String(scenes.length).padStart(2,'0');dotButtons.forEach((d,j)=>d.classList.toggle('active',j===i));progress.style.width=((i+1)/scenes.length*100)+'%'};
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)setCurrent(scenes.indexOf(e.target))}),{threshold:.62});scenes.forEach(s=>io.observe(s));
const go=d=>scenes[Math.max(0,Math.min(scenes.length-1,current+d))].scrollIntoView({behavior:'smooth'});
document.querySelector('#next').onclick=()=>go(1);document.querySelector('#prev').onclick=()=>go(-1);
document.addEventListener('keydown',e=>{if(['ArrowDown','ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();go(1)}if(['ArrowUp','ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();go(-1)}if(e.key==='Home')scenes[0].scrollIntoView();if(e.key==='End')scenes.at(-1).scrollIntoView()});
const dlg=document.querySelector('#speakerDialog');document.querySelector('#speakerBtn').onclick=()=>dlg.showModal();document.querySelector('#closeSpeaker').onclick=()=>dlg.close();dlg.onclick=e=>{if(e.target===dlg)dlg.close()};
document.querySelector('#presentBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();
const areas={tech:['Tecnologia','Código, incidentes e documentação','IA organiza contexto → sugere caminhos → profissional valida e implementa'],adm:['Administração','Relatórios, processos e cenários','IA consolida dados → identifica padrões → profissional interpreta e decide'],cont:['Ciências Contábeis','Documentos, conciliações e análises','IA extrai e classifica → sinaliza diferenças → profissional valida e responde'],rh:['Recursos Humanos','Currículos, competências e rotinas','IA organiza informações → apoia triagem → profissional contextualiza e decide'],log:['Logística','Estoque, demanda e rotas','IA cruza sinais → apoia cenários → profissional define restrições e decisão'],edu:['Educação','Aprendizagem, feedback e acompanhamento','IA organiza evidências → apoia personalização → educador interpreta e intervém']};
const card=document.querySelector('#areaCard');function render(k){const a=areas[k];card.innerHTML='<h3>'+a[0]+'</h3><p class="lead">'+a[1]+'</p><p class="mini-flow">'+a[2]+'</p>'}render('tech');
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');render(t.dataset.area)});
document.querySelectorAll('.levels button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.levels button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});
setCurrent(0);
document.querySelector('#toTop').onclick=()=>scenes[0].scrollIntoView({behavior:'smooth'});document.querySelector('#toBottom').onclick=()=>scenes.at(-1).scrollIntoView({behavior:'smooth'});

const cases={
tech:{title:'Tecnologia',tag:'Caso · Operações assistidas por IA',steps:['Logs e contexto','IA organiza sinais','Profissional investiga','Ação validada'],example:'Exemplo: reunir logs de uma aplicação, resumir padrões de erro e sugerir hipóteses. A IA reduz o trabalho de organização; diagnóstico, impacto e mudança permanecem sob validação profissional.'},
adm:{title:'Administração',tag:'Caso · Automação inteligente',steps:['Documentos e indicadores','IA extrai e consolida','Gestor compara cenários','Decisão e acompanhamento'],example:'Exemplo: consolidar relatórios recorrentes de áreas diferentes, identificar variações e produzir uma síntese inicial para uma reunião de gestão.'},
cont:{title:'Ciências Contábeis',tag:'Caso · Conciliação assistida',steps:['Documentos e transações','IA classifica','Profissional verifica divergências','Registro e decisão'],example:'Exemplo: apoiar a organização documental e sinalizar diferenças para revisão. Critérios contábeis, conformidade e responsabilidade continuam com o profissional.'},
rh:{title:'Recursos Humanos',tag:'Caso · Organização de competências',steps:['Perfis e requisitos','IA estrutura informações','RH contextualiza','Decisão humana'],example:'Exemplo: estruturar competências presentes em currículos e comparar com requisitos previamente definidos, mantendo avaliação, contexto e decisão com a equipe de RH.'},
log:{title:'Logística',tag:'Caso · Cenários operacionais',steps:['Estoque, demanda e rotas','IA cruza sinais','Profissional define restrições','Plano operacional'],example:'Exemplo: combinar histórico de demanda e estoque para apoiar cenários de reposição, que depois são avaliados à luz de prazo, custo e restrições reais.'},
edu:{title:'Educação',tag:'Caso · Personalização e feedback',steps:['Evidências de aprendizagem','IA organiza padrões','Educador interpreta','Intervenção pedagógica'],example:'Exemplo: sintetizar evidências de interação e desempenho para apoiar feedback e acompanhamento. A intervenção pedagógica é definida pelo educador.'}
};
const caseDlg=document.querySelector('#caseDialog'),caseContent=document.querySelector('#caseContent');
function openCase(){const active=document.querySelector('.tab.active');const x=cases[active.dataset.area];caseContent.innerHTML='<div class="case-head"><div><p class="case-badge">'+x.tag+'</p><h2>'+x.title+'</h2></div></div><div class="case-flow">'+x.steps.map((s,i)=>'<article><small>0'+(i+1)+'</small><strong>'+s+'</strong></article>').join('')+'</div><p class="case-example">'+x.example+'</p>';caseDlg.showModal()}
document.querySelector('#caseBtn').onclick=openCase;document.querySelector('#closeCase').onclick=()=>caseDlg.close();caseDlg.onclick=e=>{if(e.target===caseDlg)caseDlg.close()};

const mediaDlg=document.querySelector('#mediaDialog'),mediaContent=document.querySelector('#mediaContent');
const media={
timeline:{kind:'visual',title:'Da interface ao agente',text:'Uma leitura visual da evolução: interfaces conectam pessoas a sistemas; IA generativa adiciona linguagem natural; agentes passam a combinar contexto, modelos, ferramentas e ações.',visual:'<div class="demo-network"><span>PESSOA<br>contexto</span><span>IA<br>raciocínio</span><span>FERRAMENTAS<br>ação</span><span>DADOS<br>evidências</span><span>AGENTE<br>orquestração</span><span>HUMANO<br>validação</span></div>'},
agents:{kind:'video',title:'Agentes e IA em sistemas reais',text:'Vídeo oficial da NVIDIA sobre a passagem de modelos para sistemas capazes de participar de fluxos e interagir com ferramentas.',video:'https://www.youtube.com/embed/PC-7XEf0R5k',link:'https://www.youtube.com/watch?v=PC-7XEf0R5k'},
vision:{kind:'video',title:'IA multimodal em operações',text:'Exemplo oficial da NVIDIA de agentes que combinam visão, modelos de linguagem, busca e sumarização para apoiar análise de vídeo.',video:'https://www.youtube.com/embed/PW8Tl_BJNWA',link:'https://www.youtube.com/watch?v=PW8Tl_BJNWA'}
};
function openMedia(k){const m=media[k];const visual=m.kind==='video'?'<iframe src="'+m.video+'" title="'+m.title+'" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>':'<div class="media-visual">'+m.visual+'</div>';mediaContent.innerHTML='<div class="media-stage">'+visual+'<div class="media-copy"><p class="kicker">Explorar</p><h2>'+m.title+'</h2><p>'+m.text+'</p>'+(m.link?'<a href="'+m.link+'" target="_blank" rel="noopener">Abrir fonte oficial ↗</a>':'')+'</div></div>';mediaDlg.showModal()}
document.querySelectorAll('.media-btn').forEach(b=>b.onclick=()=>openMedia(b.dataset.media));document.querySelector('#closeMedia').onclick=()=>{mediaDlg.close();mediaContent.innerHTML=''};mediaDlg.onclick=e=>{if(e.target===mediaDlg){mediaDlg.close();mediaContent.innerHTML=''}};
